version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: employees
      POSTGRES_USER: akhan
      POSTGRES_PASSWORD: P@ssword1
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
    ports:
      - "8080:8080"
    depends_on:
      - postgres