### Test API endpoints using Rest client

//send form data via POST request
POST http://localhost:8080/employee
content-type: application/x-www-form-urlencoded

name=John Doe&position=Cloud Solutions Architect&startDate=-04-14-2024

### 

//GET request
GET http://localhost:8080/employee?name=John Doe

###

